const story = [
    {
        year: 2019,
        month: 5,
        day: 7,
        massage: "Wróciłem z majówki w Brennej. Mam wrażenie, że nie tylko wszyscy znajomi już programują, ale nawet wszystkie ich żony i nażeczone.",
        imgSrc: "../img/brenna.jpg",
        imgAlt: "góry",
    },
    {
        year: 2019,
        month: 5,
        day: 13,
        massage: "Odecwałem się do Łukasza. Jest najwięszym wyjadaczem IT w towarzystwie, a na majówce oferował się że może coś pomóc.",
        imgSrc: "../img/Messenger.jpg",
        imgAlt: "messanger",
    },
    {
        year: 2019,
        month: 5,
        day: 14,
        massage: "Łukasz przygotował mi rozpiskę od czego zacząć. Poleca C# jako język najbardziej przyszłościowy i dające największe możliwości. Mówi że na początek warto zacząć od jakiegoś darmowego kursu w necie.",
        imgSrc: "../img/Messenger.jpg",
        imgAlt: "messanger",
    },
    {
        year: 2019,
        month: 5,
        day: 17,
        massage: "Znalazłem na YouTube gościa który nazywa się Bob Taylor. Jest wykładowcą programowania na uczelni i prowadzi kanał Sheriff Network z kursem C# dla początkujących.",
        imgSrc: "../img/youtube.jpg",
        imgAlt: "YouTube",
    },
    {
        year: 2019,
        month: 5,
        day: 18,
        massage: "Zainstalowałem Visual Studio. No to lecimy ;)",
        imgSrc: "../img/visualstudio.jpg",
        imgAlt: "Visual Studio",
    },
    {
        year: 2019,
        month: 6,
        day: 3,
        massage: "Uczę się C# juz od jakiegoś czasu. Niby wszystko rozumiem, ale nie wiem ile udało mi się zapamiętać.",
        imgSrc: "../img/c-sharp.jpg",
        imgAlt: "C#",
    },
    {
        year: 2019,
        month: 6,
        day: 10,
        massage: "Czym dalej w las tym więcej drzew. Albo koleś przyspiesza z wiedzą, albo muszę sobie zrobić powtórkę, nie nadążam.",
        imgSrc: "../img/pytajniki.jpg",
        imgAlt: "Pytajnik",
    },
    {
        year: 2019,
        month: 6,
        day: 13,
        massage: "Wróciłem kilka lekcji wstecz. Znów wszystko wydaje się jasne, ale chyba muszę to sobie lepiej utrwalić.",
        imgSrc: "../img/ok.jpg",
        imgAlt: "OK",
    },
    {
        year: 2019,
        month: 7,
        day: 15,
        massage: "Na defiladzie z okazji Święta Wojska Polskiego widziałem się z rodzicami. Tata doradził, żeby spróbować zaprogramować coś prostego np. \"grę w życie\".",
        imgSrc: "../img/armia.jpg",
        imgAlt: "armia",
    },
    {
        year: 2019,
        month: 7,
        day: 18,
        massage: "Trochę z głowy, trochę posiłkując się kursem udało mi się napisać kilka działających linijek gry.",
        imgSrc: "../img/zycie.jpg",
        imgAlt: "życie",
    },
    {
        year: 2019,
        month: 7,
        day: 22,
        massage: "Gra działa jeżeli to ja klikam. Jeżeli proszę pomoc moją dziewczynę to od razu okazuje się że naciśnie coś czego nie przewidziałem xD",
        imgSrc: "../img/tester.jpg",
        imgAlt: "tester",
    },
    {
        year: 2019,
        month: 7,
        day: 25,
        massage: "Program wydaje się być szczelny. Nie tylko ja, ale nawet Ola nie jesteśmy W stanie jej popsuć.",
        imgSrc: "../img/ok.jpg",
        imgAlt: "ok",
    },
    {
        year: 2019,
        month: 8,
        day: 10,
        massage: "Wróciliśmy z krótkich wakacji. Na wyjeździe poznałem Paulinę. Dziewczyna za raz po szkole, wymiata we Frontendzie, a w dodatku chce zostać mentorem.",
        imgSrc: "../img/wakacje.jpg",
        imgAlt: "wakacje",
    },
    {
        year: 2019,
        month: 8,
        day: 20,
        massage: "Wróciłem do programowania mojej gry. Dodałem jakieś bajery: ramkę, możliwośc generowania nieregularnej planszy... ale kończą mi się pomysły.",
        imgSrc: "../img/c-sharp.jpg",
        imgAlt: "C#",
    },
    {
        year: 2019,
        month: 9,
        day: 10,
        massage: "Zdecydowałęm odezwać się do Pauliny. Trochę czasu minęło, ale może jeszcze o mnie pamięta. W końcu nauka z żywym człowiekiem powinna dać więcej niż kurs z YouTube.",
        imgSrc: "../img/Messenger.jpg",
        imgAlt: "messenger",
    },
    {
        year: 2019,
        month: 9,
        day: 12,
        massage: "Paulina odpisała. Okazuje się, że mój szwagier też do niej zagadał. Umówiliśmy, że przygotuje plan zajęć i będziemy pracować w trójkę.",
        imgSrc: "../img/Messenger.jpg",
        imgAlt: "messenger",
    },
    {
        year: 2019,
        month: 9,
        day: 13,
        massage: "Napisałem do szwagra. Okazuje się, że on od jakiegoś czasu uczy się programowania z kanału Pasja Informatyki. Jest już po C++, a teraz przerabia HTML i CSS.",
        imgSrc: "../img/szwagier.jpg",
        imgAlt: "szwagier",
    },
    {
        year: 2019,
        month: 9,
        day: 13,
        massage: "Przejrzałęm ten kanał co polecał Kuba. Wydaje się całkiem spoko. Sozkręca się po woli, ale przynajmniej przypomnę sobie podstawy HTML.",
        imgSrc: "../img/pasjainformatyki.jpg",
        imgAlt: "PasjaInformatyki",
    },
    {
        year: 2019,
        month: 9,
        day: 15,
        massage: "Dziś mieliśmy pierwsze spotkanie organizacyjne w twójkę. Ja, Kuba i Paulina połączyliśmy się przez Hangouts. Wygląda spoko. Można gadać przez kamerkę i udostępniać widok ekranu.",
        imgSrc: "../img/hangouts.jpg",
        imgAlt: "Hangouts",
    },
    {
        year: 2019,
        month: 9,
        day: 15,
        massage: "Okazuje się, że to na czym będziemy pracować to Visual Studio Code... niby takie podobne do Visual Studio, a jednak nie to samo.",
        imgSrc: "../img/code.jpg",
        imgAlt: "VisualStudioCode",
    },
    {
        year: 2019,
        month: 9,
        day: 18,
        massage: "W wolnyh chwilach dalej przerabiam kurs na kanale Pasja informatyki. Niby tych zajęć jest niewiele, a tu się przeplata HTML, tu CSS, tu JavaScript. Trochę tego jednak jest.",
        imgSrc: "../img/js.jpg",
        imgAlt: "JavaScript",
    },
    {
        year: 2019,
        month: 9,
        day: 19,
        massage: "Dziś mieliśmy pierwsze pełnoprawne zajęcia w trójkę. To co przedstawia Paulina to dobre uzupełnienie tego czego nauczyłem się do tej pory.",
        imgSrc: "../img/htlm.jpg",
        imgAlt: "HTML",
    },
    {
        year: 2019,
        month: 9,
        day: 20,
        massage: "Wczoraj zapomniałem napisać. Dostaliśmy od Pauliny zadanie domowe! No cóż, trzeba wziąść się w garści i się dostosować.",
        imgSrc: "../img/homework.jpg",
        imgAlt: "zadanie",
    },
    {
        year: 2019,
        month: 9,
        day: 21,
        massage: "ciąg dalszy nastąpi",
        imgSrc: "../img/cdn.jpg",
        imgAlt: "c.d.n.",
    },
];

export default story;
